name: durp
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - ipykernel
  - matplotlib
  - notebook
  - pyqt
  - fire
  - black
  - pip
  - pip:
    - tensorflow
    - tf_agents
